package com.project.edusync.enrollment.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Thread-safe registry that holds active {@link SseEmitter} instances keyed by sessionId.
 *
 * <p>A sessionId is generated by the frontend (or backend) when a bulk import job starts.
 * The frontend first subscribes to the SSE stream using that sessionId, then triggers
 * the import upload. The service emits progress events through this registry.</p>
 *
 * <p>Emitters are automatically removed when the connection is completed, timed out, or errored.</p>
 */
@Slf4j
@Component
public class SseEmitterRegistry {

    private final Map<String, SseEmitter> emitters = new ConcurrentHashMap<>();

    /**
     * Registers a new SSE emitter for the given session.
     * Automatically removes the emitter on completion, timeout, or error.
     *
     * @param sessionId Unique ID for the import session.
     * @param timeout   Emitter timeout in milliseconds (0 = no timeout).
     * @return The created {@link SseEmitter}.
     */
    public SseEmitter register(String sessionId, long timeout) {
        SseEmitter emitter = new SseEmitter(timeout);

        emitter.onCompletion(() -> {
            emitters.remove(sessionId);
            log.debug("SSE emitter completed and removed for session: {}", sessionId);
        });
        emitter.onTimeout(() -> {
            emitters.remove(sessionId);
            log.warn("SSE emitter timed out for session: {}", sessionId);
        });
        emitter.onError(ex -> {
            emitters.remove(sessionId);
            log.warn("SSE emitter error for session: {} — {}", sessionId, ex.getMessage());
        });

        emitters.put(sessionId, emitter);
        log.info("SSE emitter registered for session: {}", sessionId);
        return emitter;
    }

    /**
     * Returns the emitter for the given session, or null if not present.
     */
    public SseEmitter get(String sessionId) {
        return emitters.get(sessionId);
    }

    /**
     * Removes and completes the emitter for the given session.
     * Called after the import job is finished.
     */
    public void complete(String sessionId) {
        SseEmitter emitter = emitters.remove(sessionId);
        if (emitter != null) {
            emitter.complete();
            log.info("SSE emitter completed for session: {}", sessionId);
        }
    }

    /**
     * Removes and completes the emitter with an error.
     */
    public void completeWithError(String sessionId, Throwable ex) {
        SseEmitter emitter = emitters.remove(sessionId);
        if (emitter != null) {
            emitter.completeWithError(ex);
            log.warn("SSE emitter completed with error for session: {}", sessionId);
        }
    }
}

