package com.project.edusync.enrollment.controller;

import com.project.edusync.enrollment.service.BulkImportService;
import com.project.edusync.enrollment.model.dto.BulkImportReportDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.AllArgsConstructor;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;

/**
 * Controller to handle bulk user registration via CSV upload.
 * This endpoint is secured and accessible only to administrative roles.
 *
 * <p>To receive real-time SSE progress updates, the client must:</p>
 * <ol>
 *   <li>Generate a unique {@code sessionId} (UUID).</li>
 *   <li>Subscribe to {@code GET /api/v1/bulk-import/stream/{sessionId}} first.</li>
 *   <li>Then post the CSV here with the {@code X-Session-Id: <sessionId>} header.</li>
 * </ol>
 * <p>If {@code X-Session-Id} is omitted, the import still runs — just without SSE updates.</p>
 */
@RestController
@AllArgsConstructor
@RequestMapping("${api.url}/auth/bulk-import")
@Tag(name = "Bulk Import", description = "CSV bulk import endpoints with real-time SSE progress")
public class BulkImportController {

    private final BulkImportService bulkImportService;

    /**
     * Handles the CSV file upload for bulk user registration.
     *
     * @param userType  "students" or "staff", indicating the type of users to import.
     * @param file      The multipart CSV file containing user data.
     * @param sessionId Optional. The SSE session ID from the {@code X-Session-Id} header.
     *                  When provided, real-time progress events are pushed to the open SSE stream.
     * @return A ResponseEntity containing a BulkImportReportDTO with the final results.
     */
    @PostMapping(value = "/{userType}", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @Operation(
            summary = "Import users from CSV",
            description = "Upload a CSV file to bulk-import students or staff. " +
                          "Optionally provide X-Session-Id header for real-time SSE progress events."
    )
    public ResponseEntity<BulkImportReportDTO> handleBulkImport(
            @PathVariable String userType,
            @RequestParam("file") MultipartFile file,
            @Parameter(description = "Optional SSE session ID for real-time progress (generated by client)")
            @RequestHeader(value = "X-Session-Id", required = false) String sessionId) {

        if (file.isEmpty()) {
            return ResponseEntity.badRequest().body(
                    new BulkImportReportDTO("FAILED", "File is empty.")
            );
        }

        if (!"text/csv".equals(file.getContentType())) {
            return ResponseEntity.badRequest().body(
                    new BulkImportReportDTO("FAILED", "Invalid file type. Please upload a CSV.")
            );
        }

        try {
            BulkImportReportDTO report = bulkImportService.importUsers(file, userType, sessionId);
            return ResponseEntity.ok(report);
        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest().body(
                    new BulkImportReportDTO("FAILED", e.getMessage())
            );
        } catch (IOException e) {
            return ResponseEntity.internalServerError().body(
                    new BulkImportReportDTO("FAILED", "Error processing file: " + e.getMessage())
            );
        }
    }
}

